### ISSUE TITLE
"pch.h" not included

### ISSUE THREAD

**Issue by tmaxmax** [BataBo/Colorfulpp#1]
Can't use the header, because the precompiled header "pch.h" is missing.

**Comment by BataBo** [comment]
PCH.h is precompiled header it is automatically generated when creating new c++ project in visual studios.In this context including it is not mandatory and you can exclude it if you want

**Comment by tmaxmax** [comment]
Wouldn't it be a good idea if you would not use "using namespace std;" in the header?

**Comment by BataBo** [comment]
Understood,I'll fix in a few days,thanks for suggestions
